### PR TITLE
added korge view for android capability

### PR DESCRIPTION
**Pull request by pablocaviglia-baires**
the samples are in the following shared projects:

https://drive.google.com/file/d/1mpGcK5ytu5sguHtV-bWY7_yGVyEYZPOR/view?usp=sharing

It contains a standard korge mp project, as also an android one that consumes it in aar format.
To copy the compiled korge project into android as an aar run the script build_korge_and_copy_to_android.sh located in the root folder.

### CODE REVIEW

**Comment by soywiz** [comment]
embedded_game

Thanks, Pablo!

**Comment by soywiz** [comment]
Going to try to include the sample using this into the repo somehow.

**Comment by pablocaviglia-baires** [comment]
excellent man! great memes 👍  jajaja
regarding the sample, it's a pain in the arse to handle both android and kotlin mp projects into the same main project... tried to do it but got several errors about duplicated tasks, etc.

**Comment by soywiz** [comment]
Yeah agree. Hope this happens soon: https://www.jetbrains.com/careers/jobs/kotlin-java-developer-new-project-configuration-language-531/

Despite of that, I'm going to include the project into a folder without being directly integrated into the project itself. That should be the case for projects integrating this.

**Pull request merged**
