### PR TITLE
Add support for binding Length units to properties: points, cm, inches, percentages or values depending on the viewport dimensions

### PR DESCRIPTION
**Pull request by soywiz**
@pablocaviglia-baires

### CODE REVIEW

**Comment by soywiz** [comment]
bindLength

Thansk, Carlos!

**Review by pablocaviglia-baires — COMMENTED** [review]
Are u joking with me??? You really implemented it my man, in record time 🤯🤯🤯🤯🤯
 I've started yesterday with the android native implementation with android's canvas, reverting everything right now!!!!
Actually right now no because it's five in the morning now, jejeje, but in a couple of hours I'll ping out for details.
Thanks in huge quantities @soywiz

**Comment by soywiz** [comment]
Hahaha. I have a whole day course today and tomorrow, but was thinking about that and decided to implement it. Not sure if you will use it this time, but at least wanted to implement it so you can use in the future 😂

**Comment by pablocaviglia-baires** [comment]
Whaaaat?! Of course I'll use it now.
I'm still reviewing the code, now i understand what was you talking about
about binding 👏

**Comment by soywiz** [comment]
I have also fixed the issue you had with atomicfu/kotlin-reflect: https://github.com/korlibs/korge-next/pull/126

**Comment by pablocaviglia-baires** [comment]
👌

**Pull request merged**
