### PR TITLE
Corrected transform order in VertexShader

### PR DESCRIPTION
**Pull request by Stechmuck**
This corrects the transform order in the VertexShader in korlibs/korge#560

### CODE REVIEW

**Comment by jobe-m** [comment]
Looks good to me 👍

**Comment by soywiz** [comment]
Thanks for the fix @Stechmuck ! And thanks for checking @jobe-m !
LGTM too.

We cannot merge it yet because the CI is failing and that would break master.
I believe it fails in a reference test, so it should be easily fixable. You should be able to fix it by executing:

`./gradlew jvmTestFix`

Then comiting the updated files (probably `FSprites1.log`, `FSprites2.log`, etc.)

**Comment by Stechmuck** [comment]
I have updated the files

**Comment by soywiz** [comment]
Awesome. Thank you very much @Stechmuck !

**Pull request merged**
