### PR TITLE
Refinements to KloggerAtomicRef Proposal

### PR DESCRIPTION
**Pull request by Mayankmkh**

### CODE REVIEW

**Comment by soywiz** [comment]
Thanks @Mayankmkh !

atomic

**Comment by Mayankmkh** [comment]
@soywiz I like that you add memes to PRs. It's fun 😄

**Comment by soywiz** [comment]
It is good to know that you like them.

A game engine exists to create games. Games are mostly intended to have fun. So I thought it would make sense to have fun in the process too :)

**Comment by Mayankmkh** [comment]
giphy

**Pull request merged**
